# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.LoginLabel = QtWidgets.QLabel(self.login)
        self.LoginLabel.setGeometry(QtCore.QRect(20, 280, 640, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LoginLabel.setPalette(palette)
        self.LoginLabel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.LoginLabel.setAutoFillBackground(False)
        self.LoginLabel.setStyleSheet("background-image: url(:/icon/v1.png);")
        self.LoginLabel.setText("")
        self.LoginLabel.setObjectName("LoginLabel")
        self.pictureload = QtWidgets.QPushButton(self.login)
        self.pictureload.setGeometry(QtCore.QRect(50, 190, 170, 60))
        palette = QtGui.QPalette()
        self.pictureload.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pictureload.setFont(font)
        self.pictureload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pictureload.setStyleSheet("border-image: url(:icon/button4.png);\n"
"image: url(:/icon/image.png);")
        self.pictureload.setText("")
        self.pictureload.setObjectName("pictureload")
        self.cameraload = QtWidgets.QPushButton(self.login)
        self.cameraload.setGeometry(QtCore.QRect(460, 190, 170, 60))
        palette = QtGui.QPalette()
        self.cameraload.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cameraload.setFont(font)
        self.cameraload.setStyleSheet("border-image: url(:icon/button5.png);\n"
"image: url(:/icon/instagram.png);")
        self.cameraload.setText("")
        self.cameraload.setObjectName("cameraload")
        self.videoload = QtWidgets.QPushButton(self.login)
        self.videoload.setGeometry(QtCore.QRect(255, 190, 170, 60))
        palette = QtGui.QPalette()
        self.videoload.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.videoload.setFont(font)
        self.videoload.setStyleSheet("border-image: url(:icon/button2.png);\n"
"image: url(:/icon/video.png);")
        self.videoload.setText("")
        self.videoload.setObjectName("videoload")
        self.title = QtWidgets.QLabel(self.login)
        self.title.setGeometry(QtCore.QRect(200, 10, 600, 100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(46)
        font.setItalic(True)
        self.title.setFont(font)
        self.title.setAutoFillBackground(False)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setIndent(1)
        self.title.setObjectName("title")
        self.textBrowser = QtWidgets.QTextBrowser(self.login)
        self.textBrowser.setGeometry(QtCore.QRect(680, 280, 300, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(215, 215, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(215, 215, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(215, 215, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(215, 215, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser.setPalette(palette)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.agreelogin = QtWidgets.QPushButton(self.login)
        self.agreelogin.setGeometry(QtCore.QRect(680, 190, 300, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.agreelogin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.agreelogin.setFont(font)
        self.agreelogin.setStyleSheet("border-image: url(:icon/button3.png);")
        self.agreelogin.setObjectName("agreelogin")
        self.loginwidget = QtWidgets.QWidget(self.login)
        self.loginwidget.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.loginwidget.setStyleSheet("background-image: url(:icon/blued.png);\n"
"")
        self.loginwidget.setObjectName("loginwidget")
        self.title_2 = QtWidgets.QLabel(self.login)
        self.title_2.setGeometry(QtCore.QRect(330, 90, 600, 100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.title_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(18)
        font.setItalic(False)
        self.title_2.setFont(font)
        self.title_2.setAutoFillBackground(False)
        self.title_2.setTextFormat(QtCore.Qt.AutoText)
        self.title_2.setScaledContents(False)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setWordWrap(False)
        self.title_2.setIndent(1)
        self.title_2.setObjectName("title_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.login)
        self.textBrowser_2.setGeometry(QtCore.QRect(730, 341, 200, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_2.setPalette(palette)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.login)
        self.textBrowser_3.setGeometry(QtCore.QRect(730, 493, 200, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_3.setPalette(palette)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.login)
        self.textBrowser_4.setGeometry(QtCore.QRect(730, 645, 200, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_4.setPalette(palette)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.loginwidget.raise_()
        self.cameraload.raise_()
        self.LoginLabel.raise_()
        self.pictureload.raise_()
        self.videoload.raise_()
        self.title.raise_()
        self.textBrowser.raise_()
        self.agreelogin.raise_()
        self.title_2.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_4.raise_()
        self.stackedWidget.addWidget(self.login)
        self.selectgame = QtWidgets.QWidget()
        self.selectgame.setObjectName("selectgame")
        self.game1label = QtWidgets.QLabel(self.selectgame)
        self.game1label.setGeometry(QtCore.QRect(570, 150, 121, 131))
        self.game1label.setObjectName("game1label")
        self.game1button = QtWidgets.QPushButton(self.selectgame)
        self.game1button.setGeometry(QtCore.QRect(340, 200, 93, 28))
        self.game1button.setObjectName("game1button")
        self.stackedWidget.addWidget(self.selectgame)
        self.game1 = QtWidgets.QWidget()
        self.game1.setObjectName("game1")
        self.exit1 = QtWidgets.QPushButton(self.game1)
        self.exit1.setGeometry(QtCore.QRect(830, 20, 150, 60))
        palette = QtGui.QPalette()
        self.exit1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.exit1.setFont(font)
        self.exit1.setStyleSheet("image: url(:/icon/log-out.png);\n"
"border-image: url(:/icon/button5.png);")
        self.exit1.setText("")
        self.exit1.setObjectName("exit1")
        self.cap_control1 = QtWidgets.QPushButton(self.game1)
        self.cap_control1.setGeometry(QtCore.QRect(20, 20, 150, 60))
        palette = QtGui.QPalette()
        self.cap_control1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.cap_control1.setFont(font)
        self.cap_control1.setStyleSheet("border-image: url(:icon/button6.png);\n"
"image: url(:/icon/play.png);\n"
"")
        self.cap_control1.setText("")
        self.cap_control1.setObjectName("cap_control1")
        self.game1widget = QtWidgets.QWidget(self.game1)
        self.game1widget.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.game1widget.setStyleSheet("background-image: url(:icon/blued.png);")
        self.game1widget.setObjectName("game1widget")
        self.DisplayLabel1 = QtWidgets.QLabel(self.game1)
        self.DisplayLabel1.setGeometry(QtCore.QRect(50, 100, 900, 675))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.DisplayLabel1.setPalette(palette)
        self.DisplayLabel1.setAutoFillBackground(False)
        self.DisplayLabel1.setStyleSheet("background-image: url(:/icon/v2.png);")
        self.DisplayLabel1.setLineWidth(5)
        self.DisplayLabel1.setText("")
        self.DisplayLabel1.setObjectName("DisplayLabel1")
        self.title2 = QtWidgets.QLabel(self.game1)
        self.title2.setGeometry(QtCore.QRect(250, 10, 500, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.title2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(46)
        font.setItalic(True)
        self.title2.setFont(font)
        self.title2.setAlignment(QtCore.Qt.AlignCenter)
        self.title2.setObjectName("title2")
        self.game1widget.raise_()
        self.exit1.raise_()
        self.cap_control1.raise_()
        self.DisplayLabel1.raise_()
        self.title2.raise_()
        self.stackedWidget.addWidget(self.game1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Secret Flappy Bird"))
        self.title.setText(_translate("MainWindow", "Login System"))
        self.agreelogin.setText(_translate("MainWindow", "Checking"))
        self.title_2.setText(_translate("MainWindow", "制作人：张越 赵展维 黄炜 李嘉静"))
        self.game1label.setText(_translate("MainWindow", "TextLabel"))
        self.game1button.setText(_translate("MainWindow", "Game1"))
        self.title2.setText(_translate("MainWindow", "Flappy Bird"))

import sourse_rc
